module.exports = {
	...require('./base'),
	...require('./layout.js'),
	...require('./button.js'),
	...require('./image.js'),
	...require('./text.js'),
	...require('./progress-bar.js'),
	...require('./throbber.js'),
	...require('./list.js'),
	...require('./table.js'),
	...require('./figure.js'),
	...require('./charts'),
	...require('./forms'),
	...require('./navigation'),
}
